### PR TITLE
Add in memory users

### PR DESCRIPTION
**Pull request by spolischook**
https://github.com/symfony-cmf/standard-edition/issues/38

### CODE REVIEW

**Comment by lsmith77** [comment]
@WouterJ we removed this because it was removed from the SE, right?

**Comment by WouterJ** [comment]
@lsmith77 yes.

I don't see why we would need to add memory users to the SE. The SE doesn't configure any security (except from an anonymous firewall) and doesn't include an admin interface (so no need to protect an admin area).

Also, unless I'm missing something, #38 is about [these lines in `app_dev.php`](https://github.com/symfony-cmf/standard-edition/blob/master/web/app_dev.php#L10-18), which is not related to the Security system.

**Comment by WouterJ** [comment]
Oh well, my bad. This is related to the CreateBundle integration. However, in this case, we need to assign the `ROLE_ADMIN` role and not `ROLE_SUPER_ADMIN`. Also, I would prefer to not use parameters here, but just configure it in `security.yml`.

**Comment by dbu** [comment]
+1 for not using parameters but do it in security.yml. and add a comment around it that you want to change this in a real project?

**Comment by spolischook** [comment]
If you use in memory users you must hold all passwords in parameters.yml. If you add or remove users you need change two files. I find this way is more usable in a project with in memory users.

**Comment by dbu** [comment]
the thing is we want to strongly discourage from using this outside of demo purposes. having the passwords in plain text in a parameters.yml file is not good security

**Comment by spolischook** [comment]
so I can change "encoders" setting and live users with passwords in parameters.yml?

**Comment by WouterJ** [comment]
I highly recommend to use in memory users purely for demo purposes and use a user in a database, a custom user provider with built-in users or something else in production.

**Comment by spolischook** [comment]
@WouterJ ok so what am I gonna do? We have broken behavior in fresh installation, and we need users for fixing it. I can add a the comment like "Highly recommend to not use in memory users in the production environment"

**Comment by WouterJ** [comment]
I propose to just add the condig.yml (so no parameter) and add a comment that this is just for demo purposes and one should use another user provider in real apps, maybe even linking to the docs

**Comment by lsmith77** [comment]
ping

**Comment by spolischook** [comment]
will fix your comments, asap, thanks for reminders!

**Comment by lsmith77** [comment]
thx!

**Comment by spolischook** [comment]
done

**Comment by lsmith77** [comment]
@spolischook thanks .. can you also add a comment as noted by @WouterJ above?

**Comment by spolischook** [comment]
done

**Comment by lsmith77** [comment]
thanks!

**Pull request merged**
