### PR TITLE
Updated dependencies for CmfMenuBundle 2.0

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by WouterJ** [comment]
This should also be ready to merge

**Comment by dbu** [comment]
tests fail with You have requested a non-existent service "doctrine_phpcr.admin.default_session".

**Comment by WouterJ** [comment]
@dbu yeah, for the same reason as https://github.com/symfony-cmf/cmf-sandbox/pull/299#issuecomment-152210832 fails. This bug is fixed in https://github.com/doctrine/DoctrinePHPCRBundle/pull/214, but it was not yet added to a release (1.3.0-RC2 is not yet released). This works for the bundles as they all rely on unstable versions, while the SE and sandbox rely on stable versions (at least more stable than dev).

**Comment by dbu** [comment]
i tagged the next RC now, but this still fails. so the regression is still open?

**Comment by WouterJ** [comment]
@dbu, no SE uses a composer.lock so you first have to update the deps locally, commit the lock file and push to this repo.

**Comment by dbu** [comment]
this is a new one: 

Could not create database "/home/travis/build/symfony-cmf/standard-edition/app/app.sqlite" for connection named default

SQLSTATE[HY000] [14] unable to open database file

did something change on travis?

**Comment by WouterJ** [comment]
@dbu I got the same error on an app last week. Seems like a latest version of some package has a big bug causing this.

**Comment by dbu** [comment]
it looks like a travis file system permission problem :-(

**Comment by WouterJ** [comment]
@dbu no, it also happends locally on Windows (which does not know file system permissions like Travis does...)

**Comment by WouterJ** [comment]
@dbu see https://github.com/doctrine/DoctrineBundle/commit/9e556cb718fd436741762de1aa34197626656c49

**Comment by WouterJ** [comment]
Seems there already is a PR that fixes this: https://github.com/doctrine/DoctrineBundle/pull/483

**Pull request merged**
